### ISSUE TITLE
syntax error: unexpected end of file

### ISSUE THREAD

**Issue by astream2018** [kellobri/azure-devops-shiny-template#1]
I'm trying-out your scripts. looks like its failing.
The only changes on the yml is the removal of:
- vmImage: 'ubuntu-latest'
- group: 'RStudio Connect Vars'

I'm only using a pool with a RHEL 7.9 agent  configured.

##[section]Starting: Create Upload Deploy
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
Formatted command: . '/opt/tfsagent/_work/1/s/create-upload-deploy.sh' Azure DevOps Deployment Demo App
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /opt/tfsagent/_work/_temp/6cf1dafd-dcd7-44d0-b302-9a6db5cf32db.sh
/opt/tfsagent/_work/1/s/create-upload-deploy.sh: line 6: $'\r': command not found
/opt/tfsagent/_work/1/s/create-upload-deploy.sh: line 14: $'\r': command not found
/opt/tfsagent/_work/1/s/create-upload-deploy.sh: line 15: set: -
: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
/opt/tfsagent/_work/1/s/create-upload-deploy.sh: line 16: $'\r': command not found
/opt/tfsagent/_work/1/s/create-upload-deploy.sh: line 125: syntax error: unexpected end of file
##[error]Bash exited with code '1'.
##[section]Finishing: Create Upload Deploy

**Comment by kellobri** [comment]
@astream2018 It looks like the create-upload-deploy.sh file here isn't correctly formatted in your RHEL image because it's trying to execute the carriage return lines '\r'.

Azure Pipelines agent pool doesn't offer a standard RHEL image: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml and from what I can tell, the task I'm using (Bash@3) doesn't get tested against anything else. The task itself is open source though: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops

Could you run a test with an inline Bash task rather than a filepath and see if that makes a difference? Something simple like this? 

```
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      if [ -z "${CONNECT_SERVER}" ] ; then
          echo "The CONNECT_SERVER environment variable is not defined. It defines"
          echo "the base URL of your RStudio Connect instance."
          echo 
          echo "    export CONNECT_SERVER='http://connect.company.com/'"
          exit 1
      fi
      
      echo "${CONNECT_SERVER}"
```

**Comment by astream2018** [comment]
Hi @kellobri ,

Thank you for giving insides how to fix this. We had a slide different approach. see our yml file below.

`# RStudio Connect Deployment Pipeline:
#   1. Create, Upload, & Deploy Content
#   2. Set the Vanity URL
#   3. Update the Access Control List

trigger:
- main

pool: 'RStudio'

variables:
- name: CONTENT_DIRECTORY
  value: app-dir
- name: VANITY_NAME
  value: azure-devops-app

steps:
**- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      dos2unix create-upload-deploy.sh**
- task: Bash@3
  displayName: 'Create Upload Deploy'
  inputs:
    filePath: 'create-upload-deploy.sh'
    arguments: 'Azure DevOps Deployment Demo App'
  env:
    CONNECT_API_KEY: $(CONNECT_API_KEY)
- task: Bash@3
  displayName: 'Set Vanity URL'
  inputs:
    filePath: 'set-vanity-url.sh'
  env:
    CONNECT_API_KEY: $(CONNECT_API_KEY)
- task: Bash@3
  displayName: 'Update Access Control List'
  inputs:
    filePath: 'update-acl.sh'
  env:
    CONNECT_API_KEY: $(CONNECT_API_KEY)` 


It would be also handy to have the users which has done the last commit as the collaborator. 
Thanks in advance.
